zram_drv: workaround 5.10 bpf mandatory change
We are getting the following error due to proc_dou8vec_minmax is using const struct ctl_table *table

../drivers/block/zram/zram_drv.c:78:19: error: incompatible function pointer types initializing 'proc_handler *' (aka 'int (*)(struct ctl_table *, int, void *, unsigned long *, long long *)') with an expression of type 'int (const struct ctl_table *, int, void *, size_t *, loff_t *)' (aka 'int (const struct ctl_table *, int, void *, unsigned long *, long long *)') [-Wincompatible-function-pointer-types]
   78 |                 .proc_handler   = proc_dou8vec_minmax,
      |                                   ^~~~~~~~~~~~~~~~~~~
1 error generated.

However, we cannot get rid of the const as it is mandated by 5.10 bpf

Instead, make a function wrapper and use that instead to workaround that

Signed-off-by: Yahya Wessam <yahyawessam2002@gmail.com>